In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn import linear_model
pip install word2number

SyntaxError: invalid syntax (<ipython-input-10-8416798e616a>, line 6)

In [16]:
df = pd.read_csv('C:/Users/Suraj More/Desktop/Linear Reg/Multiple Lin/Hiring.csv')

In [17]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [18]:
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [20]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [33]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [35]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [36]:
reg.predict([[12,10,10]])

array([93747.79628651])

In [37]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [38]:
reg.intercept_

14992.651446693126

In [39]:
2922.26901502*2+2221.30909959*9+2147.48256637*6+14992.651446693126

53713.86677126313